### ISSUE TITLE
Add all item to homepage dropdowns

### ISSUE THREAD

**Issue by dashtinejad** [exirresearch/scimed#20]
Add `{ 0: 'All' }` for this fields:

- [ ] College
- [ ] Research
- [ ] Group

![image](https://cloud.githubusercontent.com/assets/8079021/23850779/1c0fe9d6-07f6-11e7-857e-1e2f652678f8.png)

**Comment by Farahzadi** [comment]
تو حالتی که داده نمیاد هم باید داشته باشیم؟

**Comment by dashtinejad** [comment]
بله
